import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Dashboard/header/Header";
import styles from "@/css/styles.module.css";
import UserSideBar from "@/components/Users/sidebars/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main className={styles.main}>
                    <Header />
                    <section className={styles.container} >
                        <UserSideBar />
                        <section className={styles.Right}>
                            {children}
                        </section>
                    </section>
                </main>
            </body>
        </html>
    );
}
